/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_habzy_video_JNI */

#ifndef _Included_com_habzy_video_JNI
#define _Included_com_habzy_video_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_habzy_video_JNI
 * Method:    adjustFD
 * Signature: (Ljava/io/FileDescriptor;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_habzy_video_JNI_adjustFD
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
